### ISSUE TITLE
A couple of debugging calls in the code

### ISSUE THREAD

**Issue by tractorcow** [sheadawson/silverstripe-userswitcher#17]
See https://github.com/sheadawson/silverstripe-userswitcher/commit/fdfd9874093ae05832302f317dc041998bbfbc86 just a heads up. :)

**Comment by sheadawson** [comment]
Oops how embarrassing =p

Fixed in https://github.com/sheadawson/silverstripe-userswitcher/commit/d684e2eb21ac6c0272de89bf82d21528911b66e9
