### ISSUE TITLE
Disable on dev/build

### ISSUE THREAD

**Issue by wernerkrauss** [sheadawson/silverstripe-userswitcher#6]
When running dev/build on 3.1.15 and changing something on Member i get an error like:

> [User Error] Couldn't run query: SELECT DISTINCT "Member"."ClassName", .... FROM "Member" WHERE ("Member"."ID" = 123) ORDER BY "Member"."Surname" ASC, "Member"."FirstName" ASC LIMIT 1 Unknown column 'Member.Foo' in 'field list'

Disabling userswitcher by putting a _manifest_exclude file in fixes this problem by now but isn't that comfortable...

**Comment by silbinarywolf** [comment]
This has been resolved in this commit:
https://github.com/sheadawson/silverstripe-userswitcher/commit/b64ac65ab6805a781309eb10b45b07a3a928db8b
